# Generated by Django 6.0.7 on 2026-07-16 14:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ad')),
                ('value', models.CharField(max_length=150, verbose_name='Qiymət')),
            ],
            options={
                'verbose_name': 'fəaliyyət',
                'verbose_name_plural': 'Fəaliyyətlər',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.TextField(verbose_name='İkon')),
                ('title', models.CharField(max_length=150, verbose_name='Başlıq')),
                ('content', models.TextField(verbose_name='Kontent')),
            ],
            options={
                'verbose_name': 'üstünlük',
                'verbose_name_plural': 'Üstünlüklər',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ad')),
                ('surname', models.CharField(max_length=50, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon nömrəsi')),
                ('note', models.TextField(verbose_name='Qeyd')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Göndərildi')),
            ],
            options={
                'verbose_name': 'müraciət',
                'verbose_name_plural': 'Müraciətlər',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Başlıq')),
                ('content', models.TextField(verbose_name='Kontent')),
                ('image', models.ImageField(upload_to='banner_imgs/', verbose_name='Şəkil')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'Bannerlər',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Başlıq')),
                ('content', models.TextField(verbose_name='Kontent')),
                ('image', models.ImageField(upload_to='service_imgs/', verbose_name='Şəkil')),
            ],
            options={
                'verbose_name': 'missiya və baxış',
                'verbose_name_plural': 'Missiyalar və Baxışlar',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Ad')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_imgs/', verbose_name='Şəkil')),
                ('degree', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dərəcə')),
                ('weight_unit', models.CharField(choices=[('KG', 'Kiloqram'), ('G', 'Qram'), ('AD', 'Ədəd'), ('TON', 'Ton')], default='KG', max_length=3, verbose_name='Çəki vahidi')),
                ('cost_price', models.FloatField(default=0, verbose_name='Maya dəyəri')),
                ('purchase_price', models.FloatField(default=0, verbose_name='Alış qiyməti')),
                ('currency', models.CharField(default='M', max_length=1, verbose_name='Valyuta')),
                ('price', models.FloatField(default=0, verbose_name='Satış qiyməti')),
                ('discount_price', models.FloatField(blank=True, null=True, verbose_name='Endirimli qiyməti')),
                ('amount', models.FloatField(default=0, verbose_name='Miqdar')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_at_purchase_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Alış yenilənmə tarixi')),
            ],
            options={
                'verbose_name': 'məhsul',
                'verbose_name_plural': 'Məhsullar',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('image', models.ImageField(upload_to='category_imgs/', verbose_name='Şəkil')),
            ],
            options={
                'verbose_name': 'məhsul kateqoriyası',
                'verbose_name_plural': 'Məhsul kateqoriyaları',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Başlıq')),
                ('image', models.ImageField(upload_to='service_imgs/', verbose_name='Şəkil')),
            ],
            options={
                'verbose_name': 'xidmət',
                'verbose_name_plural': 'xidmətlər',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_imgs/', verbose_name='Loqo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site_imgs/', verbose_name='Favikon')),
                ('about_title', models.TextField(blank=True, null=True, verbose_name='Haqqımızda başlıq')),
                ('about_content', models.TextField(blank=True, null=True, verbose_name='Haqqımızda kontent')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='site_imgs/', verbose_name='Haqqımızda şəkil')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Ünvan')),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Əlaqə nömrəsi')),
                ('about_services', models.TextField(blank=True, null=True, verbose_name='Xidmətlərimiz')),
                ('contact_title', models.TextField(blank=True, null=True, verbose_name='Əlaqə başlıq')),
                ('contact_content', models.TextField(blank=True, null=True, verbose_name='Əlaqə kontent')),
                ('contact_image', models.ImageField(blank=True, null=True, upload_to='site_imgs/', verbose_name='Əlaqə şəkil')),
            ],
            options={
                'verbose_name': 'parametr',
                'verbose_name_plural': 'Parametrlər',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.TextField(verbose_name='İkon')),
                ('link', models.URLField(max_length=256, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'sosial media',
                'verbose_name_plural': 'Sosial Media Hesabları',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Ünvan')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon nömrəsi')),
                ('status', models.CharField(blank=True, choices=[('S', 'Satış qiyməti'), ('E', 'Endirimli qiymət')], max_length=2, null=True, verbose_name='Ödəniş statusu')),
                ('website', models.CharField(blank=True, max_length=256, null=True, verbose_name='Vebsayt')),
                ('is_supplier', models.BooleanField(default=True, editable=False, verbose_name='Tədarükçü statusu')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Ümumi məbləğ')),
                ('date', models.DateField(auto_now_add=True)),
                ('add_to_sale', models.BooleanField(default=False, verbose_name='Satışa əlavə et')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'sifariş',
                'verbose_name_plural': 'Sifarişlər',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_orderitems', to='core.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orderitems', to='core.product')),
            ],
            options={
                'verbose_name': 'sifariş elementi',
                'verbose_name_plural': 'Sifariş elementləri',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1, verbose_name='Miqdar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_basketitems', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_basketitems', to='core.product', verbose_name='Məhsul')),
            ],
            options={
                'verbose_name': 'səbət elementi',
                'verbose_name_plural': 'Səbət elementləri',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Artikl')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.product')),
            ],
            options={
                'verbose_name': 'artikl',
                'verbose_name_plural': 'Artikllar',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ProductAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('content', tinymce.models.HTMLField(verbose_name='Məzmun')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_abouts', to='core.product', verbose_name='Məhsul')),
            ],
            options={
                'verbose_name': 'Məhsul məlumatı',
                'verbose_name_plural': 'Məhsul məlumatları',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_products', to='core.productcategory', verbose_name='Kateqoriya'),
        ),
        migrations.CreateModel(
            name='WantedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=500, verbose_name='Axtarış')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Axtarılma tarixi və vaxtı')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wantedproducts', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'axtarılan məhsul',
                'verbose_name_plural': 'Axtarılan məhsullar',
                'ordering': ('-id',),
            },
        ),
    ]
