# Generated by Django 6.0.7 on 2026-07-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight_unit',
        ),
        migrations.AddField(
            model_name='product',
            name='measurement_unit',
            field=models.CharField(choices=[('piece', 'Ədəd'), ('kg', 'Kiloqram')], default='piece', max_length=10, verbose_name='Ölçü vahidi'),
        ),
    ]
