# Generated by Django 5.2.16 on 2026-07-17 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_product_weight_unit_product_measurement_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'marka',
                'verbose_name_plural': 'Markalar',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'brend',
                'verbose_name_plural': 'Brendlər',
                'ordering': ('-id',),
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='measurement_unit',
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Miqdar'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Miqdar'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_products', to='core.brand', verbose_name='Marka'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_products', to='core.store', verbose_name='Brend'),
        ),
    ]
