# Generated by Django 5.2.16 on 2026-07-20 22:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_product_brand_remove_product_degree_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Miqdar'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'Ədəd'), ('kg', 'Kq'), ('metre', 'Metr')], default='piece', max_length=10, verbose_name='Ölçü vahidi'),
        ),
    ]
