# Generated by Django 6.0.7 on 2026-07-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarix')),
                ('product_price', models.FloatField(blank=True, null=True, verbose_name='Məhsul qiyməti')),
                ('payment_amount', models.FloatField(blank=True, null=True, verbose_name='Ödənilən məbləğ')),
                ('total_amount', models.FloatField(blank=True, null=True, verbose_name='Ümumi gəlir')),
                ('remaining_amount', models.FloatField(blank=True, null=True, verbose_name='Qalan məbləğ')),
                ('return_amount', models.FloatField(blank=True, null=True, verbose_name='Qaytarılan məbləğ')),
                ('action', models.CharField(default='-', max_length=250, verbose_name='Hərəkət')),
            ],
            options={
                'verbose_name': 'Müştəri hərəkəti',
                'verbose_name_plural': 'Müştəri hərəkəti',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CustomerActionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Müştəri hərəkət siyahısı',
                'verbose_name_plural': 'Müştəri hərəkət siyahıları',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Xərc',
                'verbose_name_plural': 'Xərclər',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Tarix və vaxt')),
                ('amount', models.FloatField(default=0, verbose_name='Ödənilən məbləğ')),
            ],
            options={
                'verbose_name': 'Ödəniş',
                'verbose_name_plural': 'Ödənişlər',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ProductAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarix')),
                ('incoming_product_number', models.FloatField(blank=True, null=True, verbose_name='Gələn məhsul sayı')),
                ('sold_product_number', models.FloatField(blank=True, null=True, verbose_name='Satılan məhsul sayı')),
                ('remaining_product_number', models.FloatField(blank=True, null=True, verbose_name='Qalan məhsul sayı')),
                ('return_product_number', models.FloatField(blank=True, null=True, verbose_name='Qaytarılan məhsul sayı')),
                ('action', models.CharField(default='-', max_length=250, verbose_name='Hərəkət')),
            ],
            options={
                'verbose_name': 'Məhsul hərəkəti',
                'verbose_name_plural': 'Məhsul hərəkəti',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, verbose_name='Miqdar')),
                ('price', models.FloatField(default=0, verbose_name='Alış qiyməti')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Alış tarixi')),
                ('status', models.CharField(choices=[('G', 'Gözləyir'), ('A', 'Anbarda')], default='G', max_length=1, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Məhsul alışı',
                'verbose_name_plural': 'Məhsul alışı',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'Alış siyahısı',
                'verbose_name_plural': 'Alış siyahıları',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ReturnBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('Y', 'Yararsız'), ('I', 'Işlək')], default='I', max_length=1)),
            ],
            options={
                'verbose_name': 'Geri qaytarma',
                'verbose_name_plural': 'Geri qaytarılan məhsullar',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, verbose_name='Miqdar')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='Tarix və vaxt')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Satış qiyməti')),
                ('status', models.CharField(choices=[('G', 'Gözləyir'), ('S', 'Satılıb')], default='G', max_length=1, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Məhsul satışı',
                'verbose_name_plural': 'Məhsul satışı',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='SaleList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Satış siyahısı',
                'verbose_name_plural': 'Satış siyahıları',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Stok',
                'verbose_name_plural': 'Anbar',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('currency', models.CharField(choices=[('M', 'Manat'), ('D', 'Dollar'), ('R', 'Rubl')], default='M', max_length=1)),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Tədarükçü ödənişi',
                'verbose_name_plural': 'Tədarükçü ödənişləri',
            },
        ),
    ]
