# Generated by Django 5.2.16 on 2026-07-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaction',
            name='incoming_product_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gələn məhsul sayı'),
        ),
        migrations.AlterField(
            model_name='productaction',
            name='remaining_product_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qalan məhsul sayı'),
        ),
        migrations.AlterField(
            model_name='productaction',
            name='return_product_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qaytarılan məhsul sayı'),
        ),
        migrations.AlterField(
            model_name='productaction',
            name='sold_product_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Satılan məhsul sayı'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Miqdar'),
        ),
        migrations.AlterField(
            model_name='returnback',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Miqdar'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
