# Generated by Django 5.2.16 on 2026-07-20 22:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_productaction_incoming_product_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaction',
            name='incoming_product_number',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gələn məhsul sayı'),
        ),
        migrations.AlterField(
            model_name='productaction',
            name='remaining_product_number',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Qalan məhsul sayı'),
        ),
        migrations.AlterField(
            model_name='productaction',
            name='return_product_number',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Qaytarılan məhsul sayı'),
        ),
        migrations.AlterField(
            model_name='productaction',
            name='sold_product_number',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Satılan məhsul sayı'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Miqdar'),
        ),
        migrations.AlterField(
            model_name='returnback',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Miqdar'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
